export NODE_ENV=development
export SELENIUM_USER=nome_de_um_usuario_no_github
export SELENIUM_USER_PASSWORD=senha_do_usuario
export CLIENT_ID=client_id_da_apliacao
export CLIENT_SECRET=senha_do_client
node server