set NODE_ENV=development
set SELENIUM_USER=nome_de_um_usuario_no_github
set SELENIUM_USER_PASSWORD=senha_do_usuario
set CLIENT_ID=client_id_da_apliacao
set CLIENT_SECRET=senha_do_client
protractor config/protractor.js